# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wrapper.proto
"""Generated protocol buffer code."""
from google.protobuf import (  # noqa: F401
    struct_pb2 as google_dot_protobuf_dot_struct__pb2,
)
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rwrapper.proto\x12\x07grpckit\x1a\x1cgoogle/protobuf/struct.proto"7\n\x0fWrapperResponse\x12$\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x16.google.protobuf.Valueb\x06proto3'  # noqa: E501
)


_WRAPPERRESPONSE = DESCRIPTOR.message_types_by_name["WrapperResponse"]
WrapperResponse = _reflection.GeneratedProtocolMessageType(
    "WrapperResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _WRAPPERRESPONSE,
        "__module__": "wrapper_pb2"
        # @@protoc_insertion_point(class_scope:grpckit.WrapperResponse)
    },
)
_sym_db.RegisterMessage(WrapperResponse)

if _descriptor._USE_C_DESCRIPTORS == False:  # noqa: E712

    DESCRIPTOR._options = None
    _WRAPPERRESPONSE._serialized_start = 56
    _WRAPPERRESPONSE._serialized_end = 111
# @@protoc_insertion_point(module_scope)
