K_GRPCKIT_DEBUG = "GRPCKIT_DEBUG"

K_GRPCKIT_SERVICE_SCAN_DIR = "GRPCKIT_SERVICE_SCAN_DIR"

K_GRPCKIT_TLS_SERVER_CERT = "GRPCKIT_TLS_SERVER_CERT"
K_GRPCKIT_TLS_SERVER_KEY = "GRPCKIT_TLS_SERVER_KEY"
K_GRPCKIT_TLS_CA_CERT = "GRPCKIT_TLS_CA_CERT"

K_GRPCKIT_MAX_WORKERS = "GRPCKIT_MAX_WORKERS"
K_GRPCKIT_SEND_MESSAGE_MAX_LENGHT = "GRPCKIT_SEND_MESSAGE_MAX_LENGTH"
K_GRPCKIT_RECEIVE_MESSAGE_MAX_LENGHT = "GRPCKIT_RECEIVE_MESSAGE_MAX_LENGTH"
K_GRPCKIT_OPTIONS = "GRPCKIT_OPTIONS"
